version: '3'
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データ
    environment:
      - "MYSQL_DATABASE=playframework-startup"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "3306:3306"
